apiVersion: v1
kind: Service
metadata:
  name: conversion-api
  namespace: gitlab-managed-apps
spec:
  selector:
    app: conversion
  ports:
    - protocol: TCP
      port: 12345
      targetPort: 12345
---
apiVersion: v1
kind: Service
metadata:
  name: conversion-dev-api
  namespace: gitlab-managed-apps
spec:
  selector:
    app: conversion-dev
  ports:
    - protocol: TCP
      port: 12345
      targetPort: 12345
